package com.example.localization

enum class AppLanguage(
    val code: String,
    val displayName: String,
    val nativeName: String,
    val flag: String
) {
    ENGLISH("en", "English", "English", "🌐"),
    TAMIL("ta", "Tamil", "தமிழ்", "🇮🇳"),
    HINDI("hi", "Hindi", "हिन्दी", "🇮🇳"),
    TELUGU("te", "Telugu", "తెలుగు", "🇮🇳"),
    KANNADA("kn", "Kannada", "ಕನ್ನಡ", "🇮🇳"),
    MALAYALAM("ml", "Malayalam", "മലയാളം", "🇮🇳")
}

object LocalizedStrings {
    fun get(key: String, lang: AppLanguage): String {
        return translations[lang]?.get(key) ?: translations[AppLanguage.ENGLISH]?.get(key) ?: key
    }

    private val translations = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_title" to "SAYANAK",
            "app_subtitle" to "Social Protection & Emergency Safety Network",
            "emergency_sos" to "EMERGENCY SOS",
            "hold_for_sos" to "HOLD 3 SECONDS FOR SOS",
            "sos_subtitle" to "Broadcasts GPS to 112 Police, Cyber Cell & Trusted Contacts",
            "silent_sos_hint" to "Silent SOS: Shake device 3 times or press volume down",
            "report_incident" to "Report Incident",
            "report_incident_sub" to "File confidential Anonymous, Named, or Witness report",
            "ai_assistant" to "AI Safety Assistant",
            "ai_assistant_sub" to "Gemini legal guidance, trauma triage & action steps",
            "evidence_vault" to "Evidence Vault",
            "evidence_vault_sub" to "AES-256 encrypted media with SHA-256 chain-of-custody",
            "trusted_contacts" to "Trusted Contacts",
            "trusted_contacts_sub" to "Live location sharing & safety check-in countdown",
            "impact_dashboard" to "Impact Dashboard",
            "impact_dashboard_sub" to "Verified reports, cases resolved & emergency response stats",
            "resource_center" to "Resource Center",
            "resource_center_sub" to "Legal rights, NGO directory & 24x7 crisis helplines",
            "admin_portal" to "Admin & Triage Portal",
            "admin_portal_sub" to "Case management, dispatch routing & risk heatmaps",
            "police_112" to "Police (112)",
            "women_1091" to "Women Helpline (1091)",
            "cyber_1930" to "Cyber Crime (1930)",
            "child_1098" to "Child Helpline (1098)",
            "telemanas_14416" to "Tele-MANAS (14416)",
            "ambulance_102" to "Ambulance (102)",
            "quick_camouflage" to "Camouflage Mode",
            "quick_camouflage_sub" to "Mask app as a working calculator (Unlock: 9911=)",
            "large_text" to "Large Text",
            "low_literacy" to "Visual / Low-Literacy Mode",
            "anonymous_mode" to "100% Anonymous",
            "named_mode" to "Named Report",
            "third_party_mode" to "Third-Party Witness",
            "category_domestic" to "Domestic Violence & Abuse",
            "category_harassment" to "Sexual Harassment & Stalking",
            "category_child" to "Child Abuse & Exploitation",
            "category_cyber" to "Cyber Crime & Financial Fraud",
            "category_trafficking" to "Human Trafficking & Forced Labor",
            "category_medical" to "Emergency Medical & Crisis",
            "submit_report" to "Submit Protected Report",
            "case_token" to "Case Tracking Token",
            "legal_rights" to "Legal Rights & Applicable Laws",
            "safety_checkin" to "Safety Check-In",
            "checkin_prompt" to "Are you currently safe?",
            "checkin_safe_btn" to "I am Safe",
            "checkin_help_btn" to "Send SOS Alert"
        ),
        AppLanguage.TAMIL to mapOf(
            "app_title" to "சயனக் (SAYANAK)",
            "app_subtitle" to "சமூகப் பாதுகாப்பு மற்றும் அவசர உதவி கட்டமைப்பு",
            "emergency_sos" to "அவசர SOS",
            "hold_for_sos" to "SOS-க்கு 3 வினாடிகள் அழுத்தவும்",
            "sos_subtitle" to "காவல்துறை (112) மற்றும் அவசர தொடர்புகளுக்கு ஜிபிஎஸ் அனுப்பும்",
            "silent_sos_hint" to "அமைதியான SOS: தொலைபேசியை 3 முறை அசைக்கவும்",
            "report_incident" to "சம்பவத்தை புகாரளிக்கவும்",
            "report_incident_sub" to "ரகசியமாக அல்லது பெயருடன் புகார் பதிவு செய்யவும்",
            "ai_assistant" to "AI பாதுகாப்பு உதவியாளர்",
            "ai_assistant_sub" to "சட்ட ஆலோசனை மற்றும் மனநல உதவி (Gemini AI)",
            "evidence_vault" to "சான்றுகள் பெட்டகம்",
            "evidence_vault_sub" to "AES-256 குறியாக்கம் செய்யப்பட்ட ஆவண பாதுகாப்பு",
            "trusted_contacts" to "நம்பகமான தொடர்புகள்",
            "trusted_contacts_sub" to "நேரலை இருப்பிட பகிர்வு & பாதுகாப்பு நினைவூட்டல்",
            "impact_dashboard" to "தாக்க புள்ளிவிவரங்கள்",
            "impact_dashboard_sub" to "தீர்க்கப்பட்ட வழக்குகள் மற்றும் அவசர மீட்பு விவரங்கள்",
            "resource_center" to "உதவி வள மையம்",
            "resource_center_sub" to "சட்ட உரிமைகள், தன்னார்வ தொண்டு நிறுவனங்கள் மற்றும் எண்கள்",
            "admin_portal" to "நிர்வாகி தளம்",
            "admin_portal_sub" to "வழக்கு மேலாண்மை மற்றும் கண்காணிப்பு வரைபடம்",
            "police_112" to "காவல்துறை (112)",
            "women_1091" to "பெண்கள் உதவி (1091)",
            "cyber_1930" to "சைபர் கிரைம் (1930)",
            "child_1098" to "குழந்தைகள் உதவி (1098)",
            "telemanas_14416" to "டெலி-மானாஸ் (14416)",
            "ambulance_102" to "ஆம்புலன்ஸ் (102)",
            "quick_camouflage" to "மறைவு முறை (கால்குலேட்டர்)",
            "quick_camouflage_sub" to "செயலியை கணக்கீட்டு கருவியாக மறைக்கவும் (திறக்க: 9911=)",
            "large_text" to "பெரிய எழுத்துக்கள்",
            "low_literacy" to "எளிய காட்சி முறை",
            "anonymous_mode" to "100% அநாமதேய முறை",
            "named_mode" to "பெயருடன் அறிக்கை",
            "third_party_mode" to "சாட்சி / பிறர் சார்பாக",
            "category_domestic" to "குடும்ப வன்முறை & கொடுமை",
            "category_harassment" to "பாலியல் தொல்லை & பின்தொடர்தல்",
            "category_child" to "குழந்தைகள் மீதான வன்முறை",
            "category_cyber" to "இணையதள குற்றம் & மோசடி",
            "category_trafficking" to "ஆட்கடத்தல் & கட்டாய உழைப்பு",
            "category_medical" to "அவசர மருத்துவ உதவி",
            "submit_report" to "பாதுகாப்பான புகார் அனுப்பவும்",
            "case_token" to "வழக்கு கண்காணிப்பு குறியீடு",
            "legal_rights" to "சட்ட உரிமைகள் & பிரிவுகள்",
            "safety_checkin" to "பாதுகாப்பு சரிபார்ப்பு",
            "checkin_prompt" to "நீங்கள் இப்போது பாதுகாப்பாக உள்ளீர்களா?",
            "checkin_safe_btn" to "நான் பாதுகாப்பாக உள்ளேன்",
            "checkin_help_btn" to "SOS எச்சரிக்கை அனுப்பு"
        ),
        AppLanguage.HINDI to mapOf(
            "app_title" to "सायणक (SAYANAK)",
            "app_subtitle" to "सामाजिक सुरक्षा और आपातकालीन सहायता मंच",
            "emergency_sos" to "आपातकालीन SOS",
            "hold_for_sos" to "SOS के लिए 3 सेकंड दबाए रखें",
            "sos_subtitle" to "पुलिस (112), साइबर सेल और परिजनों को तुरंत जीपीएस अलर्ट",
            "silent_sos_hint" to "साइलेंट SOS: फोन को 3 बार हिलाएं या वॉल्यूम बटन दबाएं",
            "report_incident" to "घटना की रिपोर्ट करें",
            "report_incident_sub" to "गुमनाम, नाम सहित या गवाह के रूप में सुरक्षित रिपोर्ट दर्ज करें",
            "ai_assistant" to "AI सुरक्षा सहायक",
            "ai_assistant_sub" to "कानूनी सलाह, बीएनएस धाराएं और मानसिक संबल (Gemini AI)",
            "evidence_vault" to "सुरक्षित साक्ष्य वॉल्ट",
            "evidence_vault_sub" to "AES-256 एन्क्रिप्टेड फोटो, वीडियो और डिजिटल साक्ष्य",
            "trusted_contacts" to "विश्वसनीय संपर्क",
            "trusted_contacts_sub" to "लाइव लोकेशन शेयरिंग और सुरक्षा चेक-इन टाइमर",
            "impact_dashboard" to "सामाजिक प्रभाव डैशबोर्ड",
            "impact_dashboard_sub" to "हल किए गए मामले, आपातकालीन प्रतिक्रिया और सहायता आंकड़े",
            "resource_center" to "संसाधन एवं अधिकार केंद्र",
            "resource_center_sub" to "कानूनी अधिकार, एनजीओ डायरेक्टरी और 24x7 हेल्पलाइन",
            "admin_portal" to "एडमिन व केस पोर्टल",
            "admin_portal_sub" to "केस ट्रैकिंग, त्वरित सहायता और सुरक्षा हीटमैप",
            "police_112" to "पुलिस (112)",
            "women_1091" to "महिला हेल्पलाइन (1091)",
            "cyber_1930" to "साइबर क्राइम (1930)",
            "child_1098" to "चाइल्डलाइन (1098)",
            "telemanas_14416" to "टेली-मानस (14416)",
            "ambulance_102" to "एम्बुलेंस (102)",
            "quick_camouflage" to "कैमूफ्लाज कैलकुलेटर",
            "quick_camouflage_sub" to "ऐप को कैलकुलेटर में छुपाएं (अनलॉक कोड: 9911=)",
            "large_text" to "बड़े अक्षर",
            "low_literacy" to "आइकॉन / सरल विज़ुअल मोड",
            "anonymous_mode" to "100% गोपनीय व अनाम",
            "named_mode" to "नाम सहित रिपोर्ट",
            "third_party_mode" to "तीसरे पक्ष / गवाह द्वारा",
            "category_domestic" to "घरेलू हिंसा व उत्पीड़न",
            "category_harassment" to "यौन उत्पीड़न व छेड़छाड़",
            "category_child" to "बाल शोषण व उत्पीड़न",
            "category_cyber" to "साइबर अपराध व ऑनलाइन धोखाधड़ी",
            "category_trafficking" to "मानव तस्करी व बंधुआ मजदूरी",
            "category_medical" to "आपातकालीन चिकित्सा संकट",
            "submit_report" to "सुरक्षित रिपोर्ट दर्ज करें",
            "case_token" to "केस ट्रैकिंग टोकन",
            "legal_rights" to "कानूनी अधिकार एवं धाराएं",
            "safety_checkin" to "सुरक्षा चेक-इन",
            "checkin_prompt" to "क्या आप इस समय सुरक्षित हैं?",
            "checkin_safe_btn" to "मैं सुरक्षित हूँ",
            "checkin_help_btn" to "SOS मदद भेजें"
        ),
        AppLanguage.TELUGU to mapOf(
            "app_title" to "సాయనక్ (SAYANAK)",
            "app_subtitle" to "సామాజిక రక్షణ మరియు అత్యవసర సేవల వేదిక",
            "emergency_sos" to "అత్యవసర SOS",
            "hold_for_sos" to "SOS కోసం 3 సెకన్లు నొక్కండి",
            "sos_subtitle" to "పోలీసులు (112) మరియు కుటుంబ సభ్యులకు ప్రత్యక్ష GPS సందేశం",
            "silent_sos_hint" to "సైలెంట్ SOS: ఫోన్‌ను 3 సార్లు షేక్ చేయండి",
            "report_incident" to "ఫిర్యాదు నమోదు చేయండి",
            "report_incident_sub" to "గోప్యంగా లేదా పేరుతో సురక్షితంగా రిపోర్ట్ చేయండి",
            "ai_assistant" to "AI సేఫ్టీ అసిస్టెంట్",
            "ai_assistant_sub" to "చట్టపరమైన సలహా మరియు భావోద్వేగ మద్దతు (Gemini)",
            "evidence_vault" to "ఎవిడెన్స్ వాల్ట్",
            "evidence_vault_sub" to "AES-256 ఎన్‌క్రిప్టెడ్ సాక్ష్యాల భద్రత",
            "trusted_contacts" to "నమ్మకమైన పరిచయాలు",
            "trusted_contacts_sub" to "లైవ్ లొకేషన్ మరియు సేఫ్టీ చెక్-ఇన్",
            "impact_dashboard" to "ఇంపాక్ట్ డ్యాష్‌బోర్డ్",
            "impact_dashboard_sub" to "పరిష్కరించబడిన కేసులు మరియు నివేదికలు",
            "resource_center" to "సహాయ కేంద్రం",
            "resource_center_sub" to "చట్టపరమైన హక్కులు, ఎన్జీవోలు & హెల్ప్‌లైన్‌లు",
            "admin_portal" to "అడ్మిన్ పోర్టల్",
            "admin_portal_sub" to "కేసుల నిర్వహణ మరియు హీట్‌మ్యాప్‌లు",
            "police_112" to "పోలీస్ (112)",
            "women_1091" to "మహిళా హెల్ప్‌లైన్ (1091)",
            "cyber_1930" to "సైబర్ క్రైమ్ (1930)",
            "child_1098" to "చైల్డ్‌లైన్ (1098)",
            "telemanas_14416" to "టెలి-మానస్ (14416)",
            "ambulance_102" to "అంబులెన్స్ (102)",
            "quick_camouflage" to "కాలిక్యులేటర్ మోడ్",
            "quick_camouflage_sub" to "యాప్‌ను కాలిక్యులేటర్‌గా మార్చండి (అన్‌లాక్: 9911=)",
            "large_text" to "పెద్ద అక్షరాలు",
            "low_literacy" to "విజువల్ మోడ్",
            "anonymous_mode" to "100% అనామక రిపోర్ట్",
            "named_mode" to "పేరుతో రిపోర్ట్",
            "third_party_mode" to "సాక్షి / ఇతరుల తరపున",
            "category_domestic" to "గృహ హింస & వేధింపులు",
            "category_harassment" to "లైంగిక వేధింపులు",
            "category_child" to "పిల్లలపై వేధింపులు",
            "category_cyber" to "సైబర్ క్రైమ్ & మోసాలు",
            "category_trafficking" to "మానవ అక్రమ రవాణా",
            "category_medical" to "అత్యవసర వైద్యం",
            "submit_report" to "రిపోర్ట్ సమర్పించండి",
            "case_token" to "కేస్ ట్రాకింగ్ టోకెన్",
            "legal_rights" to "చట్టపరమైన హక్కులు",
            "safety_checkin" to "సేఫ్టీ చెక్-ఇన్",
            "checkin_prompt" to "మీరు ప్రస్తుతం సురక్షితంగా ఉన్నారా?",
            "checkin_safe_btn" to "నేను సురక్షితంగా ఉన్నాను",
            "checkin_help_btn" to "SOS పంపండి"
        ),
        AppLanguage.KANNADA to mapOf(
            "app_title" to "ಸಾಯನಕ್ (SAYANAK)",
            "app_subtitle" to "ಸಾಮಾಜಿಕ ರಕ್ಷಣೆ ಮತ್ತು ತುರ್ತು ಸುರಕ್ಷತಾ ನೆಟ್‌ವರ್ಕ್",
            "emergency_sos" to "ತುರ್ತು SOS",
            "hold_for_sos" to "SOS ಗಾಗಿ 3 ಸೆಕೆಂಡುಗಳ ಕಾಲ ಒತ್ತಿಹಿಡಿಯಿರಿ",
            "sos_subtitle" to "ಪೊಲೀಸ್ (112) ಮತ್ತು ಕುಟುಂಬಕ್ಕೆ ನೇರ GPS ಎಚ್ಚರಿಕೆ",
            "silent_sos_hint" to "ಸೈಲೆಂಟ್ SOS: ಫೋನ್ ಅನ್ನು 3 ಬಾರಿ ಅಲ್ಲಾಡಿಸಿ",
            "report_incident" to "ಘಟನೆಯನ್ನು ವರದಿ ಮಾಡಿ",
            "report_incident_sub" to "ಅನಾಮಧೇಯವಾಗಿ ಅಥವಾ ಹೆಸರಿನೊಂದಿಗೆ ಸುರಕ್ಷಿತ ವರದಿ",
            "ai_assistant" to "AI ಸುರಕ್ಷತಾ ಸಹಾಯಕ",
            "ai_assistant_sub" to "ಕಾನೂನು ಮಾರ್ಗದರ್ಶನ ಮತ್ತು ಸಲಹೆ (Gemini)",
            "evidence_vault" to "ಸಾಕ್ಷ್ಯ ವಾಲ್ಟ್",
            "evidence_vault_sub" to "AES-256 ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾದ ಮಾಧ್ಯಮ ಸಂಗ್ರಹ",
            "trusted_contacts" to "ವಿಶ್ವಾಸಾರ್ಹ ಸಂಪರ್ಕಗಳು",
            "trusted_contacts_sub" to "ಲೈವ್ ಸ್ಥಳ ಹಂಚಿಕೆ ಮತ್ತು ಸುರಕ್ಷತಾ ತಪಾಸಣೆ",
            "impact_dashboard" to "ಸಾಮಾಜಿಕ ಪ್ರಭಾವ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
            "impact_dashboard_sub" to "ಪರಿಹರಿಸಲಾದ ಪ್ರಕರಣಗಳು ಮತ್ತು ಅಂಕಿಅಂಶಗಳು",
            "resource_center" to "ಸಂಪನ್ಮೂಲ ಕೇಂದ್ರ",
            "resource_center_sub" to "ಕಾನೂನು ಹಕ್ಕುಗಳು, ಎನ್‌ಜಿಒ ಮತ್ತು ಸಹಾಯವಾಣಿಗಳು",
            "admin_portal" to "ಅಡ್ಮಿನ್ ಪೋರ್ಟಲ್",
            "admin_portal_sub" to "ಪ್ರಕರಣ ನಿರ್ವಹಣೆ ಮತ್ತು ರಿಸ್ಕ್ ನಕ್ಷೆ",
            "police_112" to "ಪೊಲೀಸ್ (112)",
            "women_1091" to "ಮಹಿಳಾ ಸಹಾಯವಾಣಿ (1091)",
            "cyber_1930" to "ಸೈಬರ್ ಕ್ರೈಮ್ (1930)",
            "child_1098" to "ಮಕ್ಕಳ ಸಹಾಯವಾಣಿ (1098)",
            "telemanas_14416" to "ಟೆಲಿ-ಮಾನಸ್ (14416)",
            "ambulance_102" to "ಆಂಬ್ಯುಲೆನ್ಸ್ (102)",
            "quick_camouflage" to "ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಮೋಡ್",
            "quick_camouflage_sub" to "ಕ್ಯಾಲ್ಕುಲೇಟರ್ ಆಗಿ ಮರೆಮಾಡಿ (ಅನ್‌ಲಾಕ್: 9911=)",
            "large_text" to "ದೊಡ್ಡ ಅಕ್ಷರಗಳು",
            "low_literacy" to "ದೃಶ್ಯ ಮೋಡ್",
            "anonymous_mode" to "100% ಅನಾಮಧೇಯ ವರದಿ",
            "named_mode" to "ಹೆಸರಿನೊಂದಿಗೆ ವರದಿ",
            "third_party_mode" to "ಸಾಕ್ಷಿ / ಇತರರ ಪರವಾಗಿ",
            "category_domestic" to "ಕೌಟುಂಬಿಕ ಹಿಂಸಾಚಾರ",
            "category_harassment" to "ಲೈಂಗಿಕ ಕಿರುಕುಳ",
            "category_child" to "ಮಕ್ಕಳ ಮೇಲಿನ ದೌರ್ಜನ್ಯ",
            "category_cyber" to "ಸೈಬರ್ ಅಪರಾಧ & ವಂಚನೆ",
            "category_trafficking" to "ಮಾನವ ಕಳ್ಳಸಾಗಣೆ",
            "category_medical" to "ತುರ್ತು ವೈದ್ಯಕೀಯ ನೆರವು",
            "submit_report" to "ಸುರಕ್ಷಿತ ವರದಿ ಸಲ್ಲಿಸಿ",
            "case_token" to "ಪ್ರಕರಣ ಟ್ರ್ಯಾಕಿಂಗ್ ಟೋಕನ್",
            "legal_rights" to "ಕಾನೂನು ಹಕ್ಕುಗಳು",
            "safety_checkin" to "ಸುರಕ್ಷತಾ ಚೆಕ್-ಇನ್",
            "checkin_prompt" to "ನೀವು ಪ್ರಸ್ತುತ ಸುರಕ್ಷಿತವಾಗಿದ್ದೀರಾ?",
            "checkin_safe_btn" to "ನಾನು ಸುರಕ್ಷಿತವಾಗಿದ್ದೇನೆ",
            "checkin_help_btn" to "SOS ಕಳುಹಿಸಿ"
        ),
        AppLanguage.MALAYALAM to mapOf(
            "app_title" to "സായനക് (SAYANAK)",
            "app_subtitle" to "സാമൂഹിക സംരക്ഷണവും അടിയന്തര സുരക്ഷാ ശൃംഖലയും",
            "emergency_sos" to "അടിയന്തര SOS",
            "hold_for_sos" to "SOS-നായി 3 സെക്കൻഡ് അമർത്തിപ്പിടിക്കുക",
            "sos_subtitle" to "പോലീസ് (112), ബന്ധുക്കൾ എന്നിവർക്ക് തത്സമയ GPS സന്ദേശം",
            "silent_sos_hint" to "സൈലന്റ് SOS: ഫോൺ 3 തവണ കുലുക്കുക",
            "report_incident" to "സംഭവം റിപ്പോർട്ട് ചെയ്യുക",
            "report_incident_sub" to "രഹസ്യമായോ പേര് വെച്ചോ സുരക്ഷിതമായി റിപ്പോർട്ട് ചെയ്യാം",
            "ai_assistant" to "AI സുരക്ഷാ സഹായി",
            "ai_assistant_sub" to "നിയമോപദേശവും മാനസിക പിന്തുണയും (Gemini AI)",
            "evidence_vault" to "തെളിവ് നിലവറ (Vault)",
            "evidence_vault_sub" to "AES-256 എൻക്രിപ്റ്റ് ചെയ്ത സുരക്ഷിത സംഭരണം",
            "trusted_contacts" to "വിശ്വസ്ത കോൺടാക്റ്റുകൾ",
            "trusted_contacts_sub" to "തത്സമയ ലൊക്കേഷൻ പങ്കിടലും സുരക്ഷാ ചെക്ക്-ഇന്നും",
            "impact_dashboard" to "ഇംപാക്റ്റ് ഡാഷ്‌ബോർഡ്",
            "impact_dashboard_sub" to "പരിഹരിച്ച കേസുകളും രക്ഷാപ്രവർത്തന വിവരങ്ങളും",
            "resource_center" to "വിഭവ കേന്ദ്രം",
            "resource_center_sub" to "നിയമപരമായ അവകാശങ്ങൾ, എൻ‌ജി‌ഒകൾ, ഹെൽപ്പ് ലൈനുകൾ",
            "admin_portal" to "അഡ്മിൻ പോർട്ടൽ",
            "admin_portal_sub" to "കേസ് മാനേജ്‌മെന്റും സുരക്ഷാ മാപ്പും",
            "police_112" to "പോലീസ് (112)",
            "women_1091" to "വനിതാ ഹെൽപ്പ് ലൈൻ (1091)",
            "cyber_1930" to "സൈബർ ക്രൈം (1930)",
            "child_1098" to "ചൈൽഡ് ലൈൻ (1098)",
            "telemanas_14416" to "ടെലി-മാനസ് (14416)",
            "ambulance_102" to "ആംബുലൻസ് (102)",
            "quick_camouflage" to "കാൽക്കുലേറ്റർ മോഡ്",
            "quick_camouflage_sub" to "കാൽക്കുലേറ്ററായി മറയ്ക്കുക (തുറക്കാൻ: 9911=)",
            "large_text" to "വലിയ അക്ഷരങ്ങൾ",
            "low_literacy" to "വിഷ്വൽ മോഡ്",
            "anonymous_mode" to "100% അജ്ഞാത റിപ്പോർട്ട്",
            "named_mode" to "പേരിലുള്ള റിപ്പോർട്ട്",
            "third_party_mode" to "സാക്ഷി / മറ്റൊരാൾക്ക് വേണ്ടി",
            "category_domestic" to "ഗാർഹിക പീഡനം",
            "category_harassment" to "ലൈംഗികാതിക്രമം & ശല്യം ചെയ്യൽ",
            "category_child" to "കുട്ടികൾക്കെതിരായ പീഡനം",
            "category_cyber" to "സൈബർ കുറ്റകൃത്യങ്ങൾ & തട്ടിപ്പ്",
            "category_trafficking" to "മനുഷ്യക്കടത്ത് & നിർബന്ധിത തൊഴിൽ",
            "category_medical" to "അടിയന്തര മെഡിക്കൽ സഹായം",
            "submit_report" to "റിപ്പോർട്ട് സമർപ്പിക്കുക",
            "case_token" to "കേസ് ട്രാക്കിംഗ് ടോക്കൺ",
            "legal_rights" to "നിയമപരമായ അവകാശങ്ങൾ",
            "safety_checkin" to "സുരക്ഷാ ചെക്ക്-ഇൻ",
            "checkin_prompt" to "നിങ്ങൾ ഇപ്പോൾ സുരക്ഷിതനാണോ?",
            "checkin_safe_btn" to "ഞാൻ സുരക്ഷിതനാണ്",
            "checkin_help_btn" to "SOS അയക്കുക"
        )
    )
}
